const HEADER_TABS = {
  ADD_TAB: 'ADD_TAB',
  GET_TAB_LIST: 'GET_TAB_LIST',
  ADD_TABLE: 'ADD_TABLE',
  ADD_TABLE_HEADER: 'ADD_TABLE_HEADER',
  DELETE_TAB: 'DELETE_TAB',
  RENAME_TAB: 'RENAME_TAB',
  DELETE_TABLE: 'DELETE_TABLE',
  DELETE_TABLE_HEADER: 'DELETE_TABLE_HEADER',
  INIT_TAB_LIST: 'INIT_TAB_LIST',
  INIT_TABLE: 'INIT_TABLE',
  INIT_TABLE_HEAD: 'INIT_TABLE_HEAD',
  CHANGE_TABLE: 'CHANGE_TABLE',
  CHANGE_TABLE_HEAD: 'CHANGE_TABLE_HEAD',
  UPDATE_TABLE_CELL: 'UPDATE_TABLE_CELL',
  GET_NEW_TABLE_LIST: 'GET_NEW_TABLE_LIST',

};
export default HEADER_TABS;
